''======================================================================
''
''   splashes coordinates
''   Generated by Rel Texture Packer
''   relminator 2010
''
''======================================================================


#ifndef SPLASHES__BI
#define SPLASHES__BI


#define SPLASHES_BITMAP_WIDTH   512
#define SPLASHES_BITMAP_HEIGHT  512
#define SPLASHES_NUM_IMAGES   4


		''	Format:
		''	U,V,Width,Height



dim shared as unsigned integer splashes_texcoords(15) => {_
 0, 446, 500, 54,_				'' 0
 0, 180, 500, 165,_				'' 1
 0, 0, 500, 180,_				'' 2
 0, 345, 500, 101 }				'' 3


#endif
